"""Yarn v1 (classic) lockfile parser.

Yarn 1 lockfiles have a distinctive shape: each block is
introduced by a comment line of the form ``# THIS IS AN
AUTOGENERATED FILE. DO NOT EDIT DIRECTLY`` followed by
``<specifier>`` lines, optional ``<version>`` lines, and a
``dependencies:`` block. We walk the file with the bounded safe
YAML loader so a hostile file cannot blow up the parser.

Yarn 2+ (Berry) lockfiles are out of scope for v0.2.
"""

from __future__ import annotations

import re
from typing import Any

from app.parsers.base import (
    ParserError,
    _Collector,
    build_package_url,
    finalize_parse,
    validate_record,
)
from app.parsers.npm import _classify_unsupported_specifier
from app.providers.results import ParserResult

# Yarn classic v1 lines look like:
#   lodash@^4.17.0:
#     version "4.17.21"
#     resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#..."
#     integrity sha512-...
#     dependencies:
#       foo "^1.0.0"
_HEADER_RE = re.compile(r"^([^\s].*):\s*$")
_VERSION_RE = re.compile(r'^\s*version\s+"([^"]+)"\s*$')
_RESOLVED_RE = re.compile(r'^\s*resolved\s+"([^"]+)"\s*$')
_INTEGRITY_RE = re.compile(r"^\s*integrity\s+(\S+)\s*$")
_DEP_LINE_RE = re.compile(r"^\s{4,}([^\s].*?)\s*$")
_SECTION_RE = re.compile(r"^\s*([a-zA-Z][a-zA-Z0-9_]*):\s*$")


def _split_scoped_name(name: str) -> tuple[str | None, str]:
    if name.startswith("@"):
        scope, _, rest = name[1:].partition("/")
        if rest:
            return scope, "@" + name
    return None, name


def _name_from_specifier(specifier: str) -> str | None:
    """Extract the package name from a yarn specifier like ``"@scope/foo@^1.0.0"``."""
    if not specifier:
        return None
    s = specifier.strip().strip('"').strip("'")
    if s.startswith("@"):
        # Scoped: "@scope/name@version"
        # Find the LAST '@' that introduces the version (i.e. the
        # first '@' that is not at index 0 and is followed by a
        # version character).
        idx = s.rfind("@")
        if idx <= 0:
            return s
        return s[:idx]
    # Unscoped: "name@version" or just "name"
    idx = s.rfind("@")
    if idx < 0:
        return s
    return s[:idx]


class YarnLockParser:
    ecosystem = "npm"
    manifest_type = "yarn_lock"

    def parse(self, *, content: bytes, path: str) -> ParserResult[list[dict[str, Any]]]:
        collector = _Collector()
        try:
            text = content.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ParserError(f"yarn.lock is not valid UTF-8: {exc}") from exc

        records: list[dict[str, Any]] = []
        current: dict[str, Any] | None = None
        in_dependencies = False
        for lineno, raw_line in enumerate(text.splitlines(), start=1):
            line = raw_line.rstrip()
            if not line:
                continue
            if line.startswith("#"):
                continue
            header = _HEADER_RE.match(line)
            if header is not None:
                # Finalize previous block.
                if current is not None:
                    record = self._record_from(current, path, lineno, collector)
                    if record is not None:
                        records.append(record)
                specifier = header.group(1)
                # A single block can declare multiple specifiers separated by commas
                specifiers = [s.strip().strip('"') for s in specifier.split(",")]
                current = {
                    "specifiers": specifiers,
                    "version": None,
                    "resolved": None,
                    "integrity": None,
                    "edges": [],
                    "header_line": lineno,
                }
                in_dependencies = False
                continue
            if current is None:
                continue
            if line.startswith("  "):
                version_m = _VERSION_RE.match(line)
                if version_m is not None:
                    current["version"] = version_m.group(1)
                    continue
                resolved_m = _RESOLVED_RE.match(line)
                if resolved_m is not None:
                    current["resolved"] = resolved_m.group(1)
                    continue
                integrity_m = _INTEGRITY_RE.match(line)
                if integrity_m is not None:
                    current["integrity"] = integrity_m.group(1)
                    continue
                section_m = _SECTION_RE.match(line)
                if section_m is not None and section_m.group(1) == "dependencies":
                    in_dependencies = True
                    continue
                if in_dependencies:
                    dep_m = _DEP_LINE_RE.match(line)
                    if dep_m is not None:
                        spec = dep_m.group(1).strip().strip('"').strip("'")
                        # ``spec`` is the full ``"name version"``
                        # line; the name is the first whitespace-
                        # separated token.
                        parts = spec.split()
                        spec_token = parts[0] if parts else spec
                        child_name = _name_from_specifier(spec_token)
                        if child_name:
                            is_unsupported, kind, detail = _classify_unsupported_specifier(spec)
                            current["edges"].append(
                                {
                                    "child_name": child_name,
                                    "child_version": None,
                                    "child_specifier": spec,
                                    "child_version_source": (
                                        "UNRESOLVED" if is_unsupported or not spec else "LOCKFILE"
                                    ),
                                    "child_is_unsupported": is_unsupported,
                                    "child_unsupported_kind": kind,
                                    "child_unsupported_detail": detail,
                                    "relationship": "runtime",
                                    "depth": 1,
                                }
                            )
                        continue
                # Anything else: ignore but record a warning for
                # unfamiliar keys so operators know their lockfile
                # has odd content.
                collector.warn(
                    "yarn_lock_unfamiliar_line",
                    f"Unfamiliar yarn.lock line at {lineno}.",
                    location=path,
                )
            else:
                # A non-indented, non-header line breaks the current block.
                in_dependencies = False

        if current is not None:
            record = self._record_from(current, path, lineno, collector)
            if record is not None:
                records.append(record)

        return finalize_parse(collector, records)

    def _record_from(
        self,
        block: dict[str, Any],
        path: str,
        lineno: int,
        collector: _Collector,
    ) -> dict[str, Any] | None:
        specifiers: list[str] = block.get("specifiers") or []
        if not specifiers:
            collector.warn(
                "yarn_lock_empty_block",
                f"yarn.lock block at line {lineno} had no specifier.",
                location=path,
            )
            return None
        # All specifiers in a single block refer to the same package.
        # We use the first one to derive the name; the others are
        # recorded on the specifier field.
        first = specifiers[0]
        name = _name_from_specifier(first)
        if not name:
            collector.warn(
                "yarn_lock_invalid_name",
                f"Could not derive package name from specifier {first!r}.",
                location=path,
            )
            return None
        scope, _ = _split_scoped_name(name)
        version = block.get("version")
        integrity = block.get("integrity")
        resolved = block.get("resolved")
        edges: list[dict[str, Any]] = []
        for edge in block.get("edges", []):
            edges.append(
                {
                    "parent_name": name,
                    "parent_version": version,
                    "child_name": edge["child_name"],
                    "child_version": edge["child_version"],
                    "child_specifier": edge["child_specifier"],
                    "child_version_source": edge["child_version_source"],
                    "child_is_unsupported": edge["child_is_unsupported"],
                    "child_unsupported_kind": edge["child_unsupported_kind"],
                    "child_unsupported_detail": edge["child_unsupported_detail"],
                    "relationship": edge["relationship"],
                    "depth": edge["depth"],
                }
            )
        record: dict[str, Any] = {
            "kind": "package",
            "ecosystem": self.ecosystem,
            "package_name": name,
            "scope": scope,
            "version": version,
            "version_source": "LOCKFILE" if version else "UNRESOLVED",
            "package_url": build_package_url(self.ecosystem, name, version) if version else None,
            "relationship": "transitive",
            "direct": False,
            "development": False,
            "optional": False,
            "integrity": integrity,
            "extras": None,
            "marker": None,
            "specifier": ", ".join(specifiers),
            "is_unsupported": False,
            "unsupported_kind": None,
            "unsupported_detail": resolved,
            "source_path": path,
            "edges": edges,
        }
        validate_record(record)
        return record
