"""Complete file-tree integrity manifest for the portable payload.

LV-003 contract: the packaged portable application's integrity
record must cover EVERY regular file intended to ship inside the
payload -- the executables, every DLL / PYD, the Python runtime,
the Python packages, the pywebview / pythonnet / clr_loader
dependencies, the WebView2 payload, the frontend assets, the
Alembic configuration and migrations, the notices and licences,
and every other runtime file actually distributed. The historical
``SHA256SUMS.txt`` covered only seven user-facing top-level
files, so a payload with a modified or injected runtime file
under ``_internal/`` could pass release verification.

Security model
==============

Lockverity is UNSIGNED. This manifest is NOT code signing and
NOT publisher authentication. It establishes payload
completeness and payload integrity *relative to the build
output*: the file set and bytes the verifier sees are exactly
the file set and bytes the portable build produced. The outer
distribution verification point is the published installer /
portable hash.

Design
======

* ``PAYLOAD-MANIFEST.json`` is generated by the portable build
  AFTER ``BUILD-MANIFEST.json`` and ``SHA256SUMS.txt`` exist, so
  both of those files are covered by it.
* The manifest deliberately does NOT contain a hash of itself:
  the self-hashing problem is avoided by excluding exactly one
  path (``PAYLOAD-MANIFEST.json``) from both generation and
  verification. There is no nested trust structure.
* The verifier independently walks the payload tree and compares
  the EXPECTED path set against the ACTUAL path set BEFORE
  accepting any hashes -- an extra or missing file fails even
  when every hashed entry matches.
* Manifest entry paths are validated defensively: absolute
  paths, drive letters, UNC prefixes, ``..`` segments, empty
  segments, control characters, duplicate JSON keys, and
  case-insensitive path duplicates are all rejected. Symlinks /
  reparse points and non-regular entries in the tree are
  rejected on both the generation and the verification walk.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import stat
from pathlib import Path
from typing import Any

PAYLOAD_MANIFEST_NAME = "PAYLOAD-MANIFEST.json"

# The manifest schema version. Bump when the schema changes in a
# way older verifiers cannot understand.
MANIFEST_VERSION = 1

# Paths excluded from the manifest. The manifest itself is the
# only exclusion: it cannot contain its own hash (circularity),
# and every other regular file in the payload is covered.
EXCLUDED_PATHS: tuple[str, ...] = (PAYLOAD_MANIFEST_NAME,)

_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_DRIVE_RE = re.compile(r"^[A-Za-z]:")
_MAX_REPORTED_PATHS = 10


class PayloadManifestError(Exception):
    """Raised when a payload tree or its manifest fails verification.

    The message is operator-facing: it names the offending path
    and the reason. Build scripts convert this into their
    actionable abort message.
    """


# ---------------------------------------------------------------------
# Path normalisation and validation
# ---------------------------------------------------------------------


def normalize_entry_path(raw: object) -> str:
    """Validate and normalise a manifest entry path.

    Returns the canonical relative POSIX-style path (backslashes
    normalised to forward slashes). Raises
    :class:`PayloadManifestError` for any path that is not a
    safe relative path inside the payload root:

    * not a string / empty / contains control characters,
    * absolute POSIX paths (leading ``/``),
    * Windows drive letters (``C:...``) and any ``:`` at all,
    * UNC prefixes (a leading ``//`` after backslash
      normalisation),
    * ``..`` or ``.`` segments (path traversal),
    * empty segments (``a//b``, trailing ``/``).
    """
    if not isinstance(raw, str):
        raise PayloadManifestError(f"manifest entry path is not a string: {raw!r}")
    text = raw.strip()
    if not text:
        raise PayloadManifestError("manifest entry path is empty")
    if any(ord(ch) < 0x20 for ch in text):
        raise PayloadManifestError(f"manifest entry path contains control characters: {raw!r}")
    normalized = text.replace("\\", "/")
    if normalized.startswith("/"):
        raise PayloadManifestError(f"manifest entry path is absolute: {raw!r}")
    if _DRIVE_RE.match(normalized) or ":" in normalized:
        raise PayloadManifestError(f"manifest entry path contains a drive letter or colon: {raw!r}")
    segments = normalized.split("/")
    for segment in segments:
        if segment == "":
            raise PayloadManifestError(f"manifest entry path has an empty path segment: {raw!r}")
        if segment in ("..", "."):
            raise PayloadManifestError(f"manifest entry path escapes the payload root: {raw!r}")
    return normalized


def _collision_key(rel: str) -> str:
    """Return the case-folded key used for duplicate detection.

    The payload targets Windows (case-insensitive filesystem);
    two manifest entries differing only by case would map to the
    same file, so duplicates are detected case-insensitively.
    """
    return rel.lower()


# ---------------------------------------------------------------------
# Defensive tree walk
# ---------------------------------------------------------------------


def _is_link_or_reparse(entry: os.DirEntry[Any]) -> bool:
    """Return True when ``entry`` is a symlink or Windows reparse point.

    Junctions and volume mounts are reparse points that
    ``is_symlink()`` alone does not report; on Windows the
    ``FILE_ATTRIBUTE_REPARSE_POINT`` bit covers all of them. No
    link entry of any kind may ship inside the payload.
    """
    if entry.is_symlink():
        return True
    if os.name != "nt":
        return False
    st = entry.stat(follow_symlinks=False)
    return bool(getattr(st, "st_file_attributes", 0) & stat.FILE_ATTRIBUTE_REPARSE_POINT)


def iter_payload_files(root: Path) -> list[tuple[str, Path]]:
    """Walk ``root`` defensively and return sorted ``(relpath, path)`` pairs.

    Every entry under ``root`` must be a regular file or a plain
    directory. Symlinks, reparse points / junctions, and any
    other non-regular entry raise :class:`PayloadManifestError`.
    Links are never followed: ``root`` itself must not be one,
    and no nested link is traversed.
    """
    root = Path(root)
    if root.is_symlink():
        raise PayloadManifestError(f"payload root is a symlink: {root}")
    results: list[tuple[str, Path]] = []

    def _walk(directory: Path) -> None:
        try:
            entries = sorted(os.scandir(directory), key=lambda e: e.name)
        except OSError as exc:
            raise PayloadManifestError(f"cannot read payload directory {directory}: {exc}") from exc
        for entry in entries:
            path = directory / entry.name
            if _is_link_or_reparse(entry):
                raise PayloadManifestError(
                    f"unexpected symlink/reparse entry in payload tree: {path}"
                )
            if entry.is_dir(follow_symlinks=False):
                _walk(path)
            elif entry.is_file(follow_symlinks=False):
                results.append((path.relative_to(root).as_posix(), path))
            else:
                raise PayloadManifestError(f"unexpected non-regular entry in payload tree: {path}")

    _walk(root)
    results.sort(key=lambda pair: pair[0])
    return results


def _sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


# ---------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------


def build_payload_manifest(
    root: Path,
    *,
    product: str,
    version: str,
) -> dict[str, Any]:
    """Build the complete payload manifest for the tree at ``root``.

    Every regular file is hashed EXCEPT the manifest itself (the
    sole exclusion, keeping self-hashing non-circular). The walk
    is defensive: a symlink or non-regular entry aborts
    generation. The returned dict contains no timestamps so the
    manifest bytes are deterministic for a given tree.
    """
    files: dict[str, dict[str, Any]] = {}
    total_bytes = 0
    seen_keys: dict[str, str] = {}
    excluded_keys = {_collision_key(p) for p in EXCLUDED_PATHS}
    for rel, path in iter_payload_files(root):
        if _collision_key(rel) in excluded_keys:
            continue
        key = _collision_key(rel)
        if key in seen_keys:
            raise PayloadManifestError(
                f"payload tree contains case-duplicate paths: {seen_keys[key]} and {rel}"
            )
        seen_keys[key] = rel
        size = path.stat().st_size
        files[rel] = {"sha256": _sha256_of(path), "size": size}
        total_bytes += size
    return {
        "product": product,
        "version": version,
        "manifest_version": MANIFEST_VERSION,
        "algorithm": "sha256",
        "excluded": list(EXCLUDED_PATHS),
        "file_count": len(files),
        "total_bytes": total_bytes,
        "files": files,
    }


def render_payload_manifest(manifest: dict[str, Any]) -> str:
    """Render a manifest deterministically (sorted keys, stable JSON)."""
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def write_payload_manifest(
    root: Path,
    *,
    product: str,
    version: str,
) -> Path:
    """Write ``<root>/PAYLOAD-MANIFEST.json`` and return its path.

    Safe to re-run: the manifest excludes itself, so regenerating
    the manifest for an unchanged tree produces byte-identical
    output.
    """
    root = Path(root)
    manifest = build_payload_manifest(root, product=product, version=version)
    target = root / PAYLOAD_MANIFEST_NAME
    target.write_text(render_payload_manifest(manifest), encoding="utf-8")
    return target


# ---------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    """``object_pairs_hook`` that rejects duplicate JSON object keys.

    ``json.loads`` silently keeps the last value for a duplicated
    key; a manifest carrying a duplicated ``files`` entry (or a
    duplicated path key inside ``files``) must fail verification
    instead of being silently collapsed.
    """
    seen: set[str] = set()
    for key, _value in pairs:
        if key in seen:
            raise PayloadManifestError(f"manifest contains duplicate JSON object key: {key!r}")
        seen.add(key)
    return dict(pairs)


def _load_manifest_document(manifest_path: Path) -> dict[str, Any]:
    try:
        text = manifest_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise PayloadManifestError(
            f"cannot read payload manifest at {manifest_path}: {exc}"
        ) from exc
    try:
        document = json.loads(text, object_pairs_hook=_reject_duplicate_keys)
    except PayloadManifestError:
        raise
    except ValueError as exc:
        raise PayloadManifestError(
            f"payload manifest at {manifest_path} is not valid JSON: {exc}"
        ) from exc
    if not isinstance(document, dict):
        raise PayloadManifestError(f"payload manifest at {manifest_path} is not a JSON object")
    return document


def verify_payload_tree(
    root: Path,
    *,
    manifest_path: Path | None = None,
) -> dict[str, Any]:
    """Verify the complete payload tree at ``root`` against its manifest.

    The verifier independently walks the tree and compares the
    EXPECTED path set (manifest entries) with the ACTUAL path set
    (every regular file except the manifest itself) BEFORE
    accepting any hashes. It fails on: a modified file, a missing
    expected file, an unexpected extra file, duplicate or
    malformed manifest entries, traversal / absolute / drive
    paths, symlinks / reparse points, and non-regular entries.

    Returns a small summary dict (``file_count``, ``total_bytes``)
    on success; raises :class:`PayloadManifestError` on any
    violation.
    """
    root = Path(root)
    if manifest_path is None:
        manifest_path = root / PAYLOAD_MANIFEST_NAME
    if not manifest_path.is_file():
        raise PayloadManifestError(
            "complete payload manifest not found at "
            f"{manifest_path}; the payload predates the LV-003 "
            "complete-tree manifest or is not a canonical build. "
            "Rebuild the portable with "
            "backend/scripts/build_windows_portable.py."
        )
    document = _load_manifest_document(manifest_path)

    if document.get("manifest_version") != MANIFEST_VERSION:
        raise PayloadManifestError(
            "unsupported payload manifest_version: "
            f"{document.get('manifest_version')!r} (expected {MANIFEST_VERSION})"
        )
    if document.get("algorithm") != "sha256":
        raise PayloadManifestError(
            f"unsupported payload manifest algorithm: {document.get('algorithm')!r}"
        )
    excluded = document.get("excluded")
    if excluded != list(EXCLUDED_PATHS):
        raise PayloadManifestError(
            f"payload manifest 'excluded' must be exactly {list(EXCLUDED_PATHS)}; got {excluded!r}"
        )
    files = document.get("files")
    if not isinstance(files, dict) or not files:
        raise PayloadManifestError("payload manifest 'files' must be a non-empty object")

    # Validate every manifest entry path and entry shape, and
    # detect case-insensitive path duplicates.
    expected: dict[str, dict[str, Any]] = {}
    seen_keys: dict[str, str] = {}
    for raw_rel, entry in files.items():
        rel = normalize_entry_path(raw_rel)
        key = _collision_key(rel)
        if key in seen_keys:
            raise PayloadManifestError(
                f"manifest contains duplicate normalized paths: {seen_keys[key]} and {raw_rel!r}"
            )
        seen_keys[key] = rel
        if not isinstance(entry, dict):
            raise PayloadManifestError(f"manifest entry for {rel!r} is not an object: {entry!r}")
        digest = entry.get("sha256")
        if not isinstance(digest, str) or not _SHA256_RE.match(digest):
            raise PayloadManifestError(
                f"manifest entry for {rel!r} has a malformed sha256: {digest!r}"
            )
        size = entry.get("size")
        if not isinstance(size, int) or isinstance(size, bool) or size < 0:
            raise PayloadManifestError(f"manifest entry for {rel!r} has a malformed size: {size!r}")
        expected[rel] = {"sha256": digest, "size": size}

    # Independent walk of the actual tree. The manifest itself is
    # excluded from the actual set, exactly as it was excluded
    # from generation -- comparing like for like.
    excluded_keys = {_collision_key(p) for p in EXCLUDED_PATHS}
    actual = {
        rel: path
        for rel, path in iter_payload_files(root)
        if _collision_key(rel) not in excluded_keys
    }
    actual_keys: dict[str, str] = {}
    for rel in actual:
        key = _collision_key(rel)
        if key in actual_keys:
            raise PayloadManifestError(
                f"payload tree contains case-duplicate paths: {actual_keys[key]} and {rel}"
            )
        actual_keys[key] = rel

    # Set comparison BEFORE any hashing is accepted.
    missing = sorted(set(expected) - set(actual))
    if missing:
        sample = ", ".join(missing[:_MAX_REPORTED_PATHS])
        raise PayloadManifestError(f"payload is missing {len(missing)} expected file(s): {sample}")
    extra = sorted(set(actual) - set(expected))
    if extra:
        sample = ", ".join(extra[:_MAX_REPORTED_PATHS])
        raise PayloadManifestError(
            f"payload contains {len(extra)} unexpected extra file(s): {sample}"
        )

    # Hash comparison.
    total_bytes = 0
    for rel in sorted(expected):
        path = actual[rel]
        info = expected[rel]
        actual_size = path.stat().st_size
        if actual_size != info["size"]:
            raise PayloadManifestError(
                f"payload file size mismatch for {rel!r}: manifest says "
                f"{info['size']} bytes, actual is {actual_size} bytes"
            )
        actual_digest = _sha256_of(path)
        if actual_digest != info["sha256"]:
            raise PayloadManifestError(
                f"payload file SHA-256 mismatch for {rel!r}: manifest says "
                f"{info['sha256']}, actual is {actual_digest}"
            )
        total_bytes += actual_size

    declared_count = document.get("file_count")
    if declared_count is not None and declared_count != len(expected):
        raise PayloadManifestError(
            f"manifest file_count is {declared_count} but the manifest lists {len(expected)} files"
        )
    return {"file_count": len(expected), "total_bytes": total_bytes}
