; =====================================================================
; Lockverity v2.1 Windows x64 per-user installer
; =====================================================================
;
; Committed source. Built with Inno Setup 6.7.3
; (https://jrsoftware.org/isdl.php, publisher: jrsoftware.org).
; The compiler is fetched and verified by the project's build script;
; this file is consumed by the canonical
; `python backend\scripts\build_windows_installer.py` command.
;
; The installer is per-user, x64, no admin / no UAC, and embeds the
; accepted v2.1 Part B3A portable payload as-is. It does not modify
; the operator's PATH, does not install a service, does not register
; autorun, does not phone home, and does not include code signing
; (the release is unsigned).
;
; The stable ``AppId`` below is the per-user uninstallation key the
; Windows uninstaller uses to identify the application. **Do not
; change it**: changing the AppId causes Windows to treat a new
; installer as a *different* application and the existing
; per-user uninstaller entry becomes orphaned.
;
; =====================================================================

#define MyAppName "Lockverity"
#define MyAppDisplayName "Lockverity"
#define MyAppVersion "2.1.0"
#define MyAppPublisher "Lockverity Contributors"
#define MyAppURL "https://github.com/namanparikh11/lockverity"
#define MyAppCopyright "(C) Lockverity Contributors"
#define MyAppExeName "Lockverity.exe"
#define MyAppCliExeName "lockverity-cli.exe"

; Stable per-user AppId. See the comment block above before
; changing this value. The exact GUID used here is committed
; permanently for v2.1 and all future Lockverity Windows installers.
#define MyAppId "{{E5B0C0F4-7C42-4D6A-9B17-1A2B3C4D5E6F}"

; The accepted v2.1 Part B3A portable payload is extracted to this
; subdirectory of the install dir. The same layout is preserved so
; the frozen binaries run unchanged.
#define MyAppPayloadDir "app"

[Setup]
; Stable AppId (Windows uninstaller key) -- DO NOT CHANGE.
AppId={#MyAppId}
AppName={#MyAppDisplayName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppCopyright={#MyAppCopyright}
AppReadmeFile=docs\windows-installer.md

; Per-user, x64 only. No admin, no UAC. The installer runs in the
; non-elevated context of the current user.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
ArchitecturesInstallIn64BitMode=x64compatible

; Per-user install path. ``{localappdata}\Programs\<AppName>`` is
; the Windows-recommended location for per-user programs and is
; outside ``Program Files`` (which requires elevation). Paths with
; spaces and Unicode are supported. (Note: the constant is
; ``{localappdata}`` — there is no ``{autolocalappdata}``. The
; ``auto`` prefix in Inno Setup constants is reserved for the
; system-vs-user profile resolution (``{autopf}``,
; ``{autoprograms}``, ``{autostartmenu}``, etc.) and
; ``{localappdata}`` is already inherently per-user.)
DefaultDirName={localappdata}\Programs\{#MyAppName}
DisableProgramGroupPage=yes
AllowNoIcons=yes
DisableDirPage=auto
AlwaysShowComponentsList=no

; Modern wizard look.
WizardStyle=modern
WizardSizePercent=120

; Compress the payload with the standard Inno lzma compression.
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes

; Output filename (the final filename is determined by the build
; script via the ``/OutputBaseFilename`` flag).
; The output *directory* is also passed by the build script as
; the ``/OutputDir=<absolute-path>`` command-line flag, so no
; ``OutputDir`` directive is needed in this .iss. Declaring
; ``OutputDir=dist`` here used to be paired with the
; ``DiskDirectory`` legacy directive (both predate Inno Setup
; 5.5) but is no longer required: leaving it out lets the
; ``/OutputDir`` command-line flag take effect cleanly.
OutputBaseFilename=Lockverity-{#MyAppVersion}-windows-x64-setup

; Approved Lockverity icon, used for the installer EXE, the
; uninstaller, and the installed application shortcuts. The
; underlying ICO is a packaging derivative of the approved
; favicon (16/32/48 BMP + 256x256 PNG, generated by
; ``backend\scripts\generate_exe_icon.py``).
SetupIconFile=..\pyinstaller\favicon-exe.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

; We sign nothing. The build script records the unsigned status in
; the external ``INSTALLER-MANIFEST.json``. The canonical Inno Setup
; declaration is ``SignedUninstaller=no``; the previous ``SignTool=Skip``
; line was invalid ISCC syntax (it is not a recognized directive value
; and the ``SignTool`` directive is only meaningful for the compiler's
; *runtime* signing pipeline, which we do not use). Leaving it out
; entirely is the correct, supported way to say "do not sign".
SignedUninstaller=no

; Application mutex: the running launcher and CLI both share a
; named mutex keyed on this AppId so the installer can detect
; a live instance at install / uninstall time and request a
; graceful stop.
AppMutex={#MyAppId},Global\{#MyAppId}

; Surface any install-time error instead of silently exiting
; with a generic code. (There is no ``ShowCmdLineHelp`` [Setup]
; directive in Inno Setup 6.7.3 — that name is from an older
; Inno Setup version and the compiler reports it as
; ``Unrecognized [Setup] section directive``. The default
; behavior in 6.7.3 already prints the /HELP /? summary when
; Setup is run with no arguments, which is what we want.)
; Non-blocking error UI for the silent installer; the build
; script captures the install log separately.
SetupLogging=yes

; Compression: keep the .exe self-contained (no separate archive).
; The installer is a single offline EXE. ``DiskSpanning=no`` is the
; only directive needed in Inno Setup 6.7.3 — the legacy
; ``SlicesPerDisk`` and ``DiskDirectory`` directives are not
; recognised in 6.7.3 (they are holdovers from 2.x/3.x-era Inno
; Setup and the compiler reports them as
; ``Unrecognized [Setup] section directive``).
DiskSpanning=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
; BeCalm: do not let the user see Inno's internal jargon.
BeveledLabel=Lockverity v{#MyAppVersion} setup
SetupWindowTitle=Lockverity Setup
FinishedLabelMessage=Lockverity has been installed on your computer.%n%nThe application launches in your default browser when you click Finish.%n%nYour runtime data, databases and logs are stored in:%n  %1
FinishedHeadingMessage=Completing the Lockverity Setup Wizard

[Files]
; The accepted v2.1 Part B3A payload is staged into a sibling
; ``payload/`` directory by the build script, which also verifies
; every file's hash against the accepted BUILD-MANIFEST. The
; payload is copied verbatim into ``{app}\app\`` so the
; frozen binaries run unchanged. The installer never rebuilds
; the application.
Source: "payload\*"; DestDir: "{app}\{#MyAppPayloadDir}"; \
    Flags: "ignoreversion recursesubdirs createallsubdirs"

; Copy the license, manifest, notices and SHA256SUMS to the
; installation root so the operator can verify provenance after
; install (and so the uninstaller does not delete them when the
; user chooses to remove ``{app}\app\``).
Source: "root_extra\*"; DestDir: "{app}"; Flags: "ignoreversion recursesubdirs"

; The approved 256x256 ICO for the Start Menu and desktop
; shortcut. Same ICO used as the installer's SetupIconFile.
; ``ignoreversion`` skips the version-stamp comparison so the
; ICO is always copied verbatim; the source file is staged by
; the build script so a runtime check is unnecessary.
Source: "..\pyinstaller\favicon-exe.ico"; DestDir: "{app}"; \
    Flags: "ignoreversion"

[Icons]
; Start Menu shortcut under a dedicated Lockverity folder. The
; uninstaller removes this entry by following the standard
; ``{group}\`` rule.
Name: "{group}\{#MyAppDisplayName}"; Filename: "{app}\{#MyAppExeName}"; \
    IconFilename: "{app}\{#MyAppExeName}"; IconIndex: 0; \
    Comment: "Launch Lockverity"
Name: "{group}\Lockverity documentation"; Filename: "{app}\docs\windows-installer.md"; \
    IconFilename: "{app}\{#MyAppExeName}"; IconIndex: 0; \
    Comment: "Lockverity installer documentation"
Name: "{group}\Uninstall {#MyAppDisplayName}"; Filename: "{uninstallexe}"; \
    IconFilename: "{app}\{#MyAppExeName}"; IconIndex: 0; \
    Comment: "Uninstall Lockverity"

; Optional desktop shortcut. Unchecked by default per spec.
Name: "{commondesktop}\{#MyAppDisplayName}"; Filename: "{app}\{#MyAppExeName}"; \
    IconFilename: "{app}\{#MyAppExeName}"; IconIndex: 0; \
    Comment: "Launch Lockverity"; Tasks: "desktopicon"

[Tasks]
; Optional desktop shortcut. Off by default. The user can opt
; in via the wizard.
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
; Create the uninstall log parent (Inno writes
; ``unins<id>.dat`` next to ``unins<id>.exe``).
Name: "{app}"

[UninstallDelete]
; Per-user, clean uninstall: remove the install root and the
; Start Menu / desktop shortcuts, but DO NOT touch
; ``%LOCALAPPDATA%\Lockverity\`` (the runtime data home). The
; uninstaller surfaces a message pointing the operator at the
; retained data path and the manual data-removal command.
Type: filesandordirs; Name: "{app}\{#MyAppPayloadDir}"
Type: filesandordirs; Name: "{app}\docs"
Type: filesandordirs; Name: "{app}\favicon-exe.ico"

[Code]
// =====================================================================
// Lifecycle handling: install, reinstall, uninstall
// =====================================================================
//
// The installer must not silently delete a running instance or
// confuse a same-named external process with the installed
// Lockverity. All lifecycle decisions go through the matching
// installed ``lockverity-cli.exe`` so the Part B2 identity
// protections (PID + creation time + instance UUID + module)
// are honoured end-to-end. The installer never terminates a
// process based on a PID alone.

const
    INSTALL_PAYLOAD_DIR = 'app';
    // Stable AppId mirrored in the [Setup] section. Used as the
    // per-user uninstaller key and as the cross-process mutex
    // name the runtime publishes at startup.
    APP_ID = '{E5B0C0F4-7C42-4D6A-9B17-1A2B3C4D5E6F}';
    // Path of the matching standard installed CLI. The CLI is the
    // authoritative entry point for the runtime lifecycle; the
    // installer does not spawn the GUI launcher for lifecycle
    // decisions because the launcher is designed for an
    // interactive operator, not for a non-interactive installer.
    CLI_RELATIVE = 'app\\lockverity-cli.exe';
    // Max time the installer will wait for a graceful stop.
    GRACEFUL_STOP_TIMEOUT_S = 30;

// helper: build the runtime-home path the installed CLI writes
// to. The path matches the standard Part B1/B2 location.
function StandardRuntimeHome: string;
begin
    // LOCALAPPDATA\Lockverity\run\lockverity.state.json
    Result := ExpandConstant('{localappdata}') + '\Lockverity\run\lockverity.state.json';
end;

function StateFilePath: string;
begin
    Result := StandardRuntimeHome;
end;

// helper: read the state file (best-effort, returns empty string
// on any error). The installer is conservative: a missing or
// unparseable state file is treated as "no live instance".
function TryReadStateFile(const Path: string): string;
var
    Lines: TArrayOfString;
    Buffer: string;
begin
    Result := '';
    if not FileExists(Path) then exit;
    if not LoadStringsFromFile(Path, Lines) then exit;
    if GetArrayLength(Lines) < 1 then exit;
    Buffer := '';
    // The CLI writes the state file as pretty-printed JSON on a
    // single line. We do not need a real JSON parser here; we
    // just need the pid and the instance_id substring. If the
    // file looks broken we return empty and the caller treats
    // the install as "no live instance".
    Buffer := Trim(Lines[0]);
    Result := Buffer;
end;

// helper: invoke the installed ``lockverity-cli.exe`` and return
// the stdout. The CLI is the authoritative entry point and
// exposes the documented Part B2 lifecycle (``status`` /
// ``stop``). We use ``/C`` redirection so the child inherits a
// console; this matches the operator-visible behaviour and
// keeps the lifecycle path identical to the documented one.
function RunCliSync(const Args: string; const TimeoutS: Integer): string;
var
    Exe: string;
    CmdLine, StdOut: string;
    ResultCode: Integer;
    ExecOk: Boolean;
begin
    Result := '';
    Exe := ExpandConstant('{app}') + '\' + CLI_RELATIVE;
    Log('B3B RunCliSync: exe=' + Exe);
    Log('B3B RunCliSync: args=' + Args);
    if not FileExists(Exe) then
    begin
        Log('B3B RunCliSync: Exe not found');
        exit;
    end;
    CmdLine := '"' + Exe + '" ' + Args;
    ExecOk := Exec(CmdLine, '', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Log('B3B RunCliSync: exec_ok=' + IntToStr(Integer(ExecOk)) + ' result_code=' + IntToStr(ResultCode));
    if not ExecOk then exit;
    StdOut := '';
    // ``Exec`` does not return stdout directly; ``ExecAsUser``
    // would require a temporary script. The CLI is well-behaved
    // and exits with rc=0 for ``status --json`` when the
    // instance is healthy. We rely on the exit code here and
    // do not need stdout content.
    if ResultCode <> 0 then
    begin
        Result := 'rc=' + IntToStr(ResultCode);
    end
    else
        Result := 'ok';
end;

// Detect a live installed instance via the documented state file
// + Part B2 identity verification. We call the installed
// ``lockverity-cli.exe status --json`` so the live-identity
// check (PID + creation time + instance UUID) runs in the
// authoritative code path.
function HasLiveInstance: Boolean;
var
    Rc: string;
begin
    Result := False;
    // The CLI is the authority. ``status`` exits 0 only when
    // a verified live instance is recorded in the state file.
    Rc := RunCliSync('status', 15);
    Result := (Rc = 'ok');
    Log('B3B HasLiveInstance: status_rc=' + Rc);
end;

// Request a graceful stop via the installed CLI. We block until
// the CLI exits 0 (instance is verified stopped) or the bounded
// timeout elapses. We never terminate a process by PID alone.
function RequestGracefulStop: Boolean;
var
    Rc: string;
    Elapsed, Deadline: Double;
begin
    Result := False;
    Rc := RunCliSync('stop', GRACEFUL_STOP_TIMEOUT_S);
    Result := (Rc = 'ok');
    Log('B3B RequestGracefulStop: stop_rc=' + Rc);
end;

// Called by Inno Setup before the installer replaces files. If a
// verified live instance is recorded, the installer asks the
// operator to close it before continuing.
function ShouldSkipPage(PageID: Integer): Boolean;
begin
    Result := False;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
    HasLive: Boolean;
    PromptResult: Integer;
begin
    Result := '';
    HasLive := HasLiveInstance();
    if HasLive then
    begin
        // A live instance is using the locked files. In
        // interactive (wizard) mode the operator is shown a
        // ``MB_RETRYCANCEL`` prompt and can either close the
        // instance and click Retry, or cancel the install. In
        // silent mode (``/VERYSILENT`` / ``/SUPPRESSMSGBOXES``)
        // the operator has explicitly opted out of UI; we
        // attempt a graceful stop via the installed CLI and
        // abort the install if it cannot be verified. The
        // installer is non-elevated so we never terminate the
        // process; a silent partial upgrade would leave the
        // locked files in an inconsistent state, which is worse
        // than an aborted install with a clear actionable error.
        if WizardSilent then
        begin
            if not RequestGracefulStop() then
            begin
                Result := 'Lockverity is still running and could not be stopped gracefully. Close Lockverity and re-run the installer.';
            end
            else if HasLiveInstance() then
            begin
                Result := 'Lockverity is still running after the graceful stop. Close Lockverity and re-run the installer.';
            end;
        end
        else
        begin
            PromptResult := MsgBox(
                'Lockverity is currently running.' + #13#10 + #13#10 +
                'The installer cannot replace the application while the runtime is loaded.' + #13#10 +
                'Please close Lockverity (right-click the system tray or taskbar icon) and click Retry, or Cancel to abort the install.' + #13#10 + #13#10 +
                'When Lockverity has stopped, click Retry to continue.',
                mbError, MB_RETRYCANCEL);
            if PromptResult = IDRETRY then
            begin
                // Operator confirms they have closed the
                // instance. Re-check the state file before
                // proceeding.
                if HasLiveInstance() then
                begin
                    Result := 'Lockverity is still running. Please close it and try again.';
                end;
            end
            else
                Result := 'Install cancelled by operator.';
        end;
    end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
    // The post-install ``Run`` action is gated on
    // ``ShouldRunPostInstall`` so silent installs skip it.
end;

// After the files are in place, the installed CLI can be invoked
// by the operator from a Start Menu shortcut. The post-install
// ``Launch Lockverity`` checkbox is handled by the ``Run`` entry
// below.
function ShouldRunPostInstall: Boolean;
begin
    // ``CmdLineParam: 'NoRun'`` is set by the ``/VERYSILENT`` /
    // ``/SUPPRESSMSGBOXES`` switches. Honour it: never auto-launch
    // in silent / unattended mode.
    Result := (ExpandConstant('{param:NoRun|NoRun}') <> 'NoRun');
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
    // ``CurUninstallStepChanged`` runs at each uninstall phase.
    // We use the pre-uninstall step to request a graceful
    // shutdown of the installed instance. The interactive
    // (wizard) mode shows a non-blocking informational
    // MsgBox if the graceful stop fails; the silent mode
    // never shows UI and just logs to the install log.
    if CurUninstallStep = usUninstall then
    begin
        if HasLiveInstance() then
        begin
            if not RequestGracefulStop() then
            begin
                if not WizardSilent then
                begin
                    MsgBox(
                        'Lockverity is still running. The uninstaller will continue and remove the application files, but you may need to close Lockverity manually before the next install.',
                        mbInformation, MB_OK);
                end
                else
                begin
                    Log('B3B uninstall: live instance did not stop gracefully; continuing uninstall');
                end;
            end;
        end;
    end;
end;

// Surfaces the retained-data path on uninstall so the operator
// knows where their databases, logs and uploads live. The
// ``CurUninstallProgressChanged`` event handler's parameter
// type is ``Integer`` (a 0..100 progress percentage); the
// type-name ``CurUninstallProgress`` is the unit the event is
// declared in and is not itself a usable type for the
// parameter declaration.
procedure CurUninstallProgressChanged(CurProgress: Integer);
begin
    // No-op: the retained-data path is shown in the final
    // uninstall confirmation dialog below.
end;

procedure UninstallAfterSuccess();
begin
    // ``UninstallAfterSuccess`` is called when the uninstall
    // finishes. We surface the retained-data path; the operator
    // is responsible for the optional manual data-removal step
    // (documented in ``docs\windows-installer.md``). The
    // informational MsgBox is suppressed in silent mode so the
    // unattended uninstall can complete without UI; the
    // retained-data path is also written to the install log so
    // an operator reviewing the log has the same information.
    if not WizardSilent then
    begin
        MsgBox(
            'Lockverity has been removed from this computer.' + #13#10 + #13#10 +
            'Your runtime data, databases and logs were preserved in:' + #13#10 +
            '  ' + ExpandConstant('{localappdata}') + '\Lockverity' + #13#10 + #13#10 +
            'To remove the data manually, see the "Removing runtime data" section in the Lockverity documentation.',
            mbInformation, MB_OK);
    end
    else
    begin
        Log('B3B uninstall: complete. Retained data at ' + ExpandConstant('{localappdata}') + '\Lockverity');
    end;
end;
