"""initial schema

Revision ID: 7efc41b356da
Revises: 
Create Date: 2026-07-11 20:07:51.940948
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efc41b356da'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_advisory_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=2048), nullable=True),
    sa.Column('details_url', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advisories')),
    sa.UniqueConstraint('source', 'source_advisory_id', name='uq_advisories_source_source_id')
    )
    with op.batch_alter_table('advisories', schema=None) as batch_op:
        batch_op.create_index('ix_advisories_canonical_id', ['canonical_id'], unique=False)
        batch_op.create_index('ix_advisories_published_at', ['published_at'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('GITHUB', 'UPLOADED_ARCHIVE', name='repository_source_type'), nullable=False),
    sa.Column('provider', sa.Enum('GITHUB', 'LOCAL_UPLOAD', name='repository_provider'), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.String(length=512), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'UNKNOWN', name='repository_visibility'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('last_provider_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('canonical_url', name='uq_repositories_canonical_url'),
    sa.UniqueConstraint('provider', 'owner', 'name', name='uq_repositories_provider_owner_name')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index('ix_repositories_provider_owner', ['provider', 'owner'], unique=False)
        batch_op.create_index('ix_repositories_source_type', ['source_type'], unique=False)

    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED', name='scan_status'), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'UPLOAD', 'SCHEDULED', 'API', name='scan_trigger_type'), nullable=False),
    sa.Column('requested_ref', sa.String(length=255), nullable=True),
    sa.Column('resolved_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('analyzer_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_summary', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(resolved_commit_sha IS NULL) OR (length(resolved_commit_sha) >= 7)', name=op.f('ck_scan_runs_resolved_sha_length')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_scan_runs_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_runs'))
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index('ix_scan_runs_repository_id', ['repository_id'], unique=False)
        batch_op.create_index('ix_scan_runs_repository_id_created_at', ['repository_id', 'created_at'], unique=False)
        batch_op.create_index('ix_scan_runs_status', ['status'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('DEPENDENCY', 'VULNERABILITY', 'WORKFLOW', 'REPOSITORY_POSTURE', 'LICENCE', 'PROVIDER', 'DATA_QUALITY', name='finding_category'), nullable=False),
    sa.Column('severity', sa.Enum('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', 'UNKNOWN', name='finding_severity'), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CONFIRMED', 'UNKNOWN', name='finding_confidence'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.String(length=2048), nullable=False),
    sa.Column('remediation', sa.String(length=4096), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('location_path', sa.String(length=1024), nullable=True),
    sa.Column('location_start_line', sa.Integer(), nullable=True),
    sa.Column('location_end_line', sa.Integer(), nullable=True),
    sa.Column('stable_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'ACCEPTED', 'SUPPRESSED', name='finding_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(location_start_line IS NULL) OR (location_end_line IS NULL) OR (location_end_line >= location_start_line)', name=op.f('ck_findings_range_consistent')),
    sa.CheckConstraint('length(evidence_json) <= 65536', name=op.f('ck_findings_evidence_bounded')),
    sa.CheckConstraint('location_end_line IS NULL OR location_end_line > 0', name=op.f('ck_findings_end_line_positive')),
    sa.CheckConstraint('location_start_line IS NULL OR location_start_line > 0', name=op.f('ck_findings_start_line_positive')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_findings_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_findings_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('scan_run_id', 'stable_key', name='uq_findings_scan_run_id_stable_key')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_category', ['category'], unique=False)
        batch_op.create_index('ix_findings_repository_id', ['repository_id'], unique=False)
        batch_op.create_index('ix_findings_rule_id', ['rule_id'], unique=False)
        batch_op.create_index('ix_findings_scan_run_id', ['scan_run_id'], unique=False)
        batch_op.create_index('ix_findings_severity', ['severity'], unique=False)

    op.create_table('manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('manifest_type', sa.String(length=64), nullable=False),
    sa.Column('ecosystem', sa.String(length=64), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('parse_status', sa.Enum('NOT_PARSED', 'PARSED', 'PARTIAL', 'FAILED', name='manifest_parse_status'), nullable=False),
    sa.Column('parse_warning_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("path NOT LIKE '/%'", name=op.f('ck_manifests_path_no_leading_slash')),
    sa.CheckConstraint('length(path) > 0', name=op.f('ck_manifests_path_not_empty')),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_manifests_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manifests')),
    sa.UniqueConstraint('scan_run_id', 'path', name='uq_manifests_scan_run_id_path')
    )
    with op.batch_alter_table('manifests', schema=None) as batch_op:
        batch_op.create_index('ix_manifests_ecosystem', ['ecosystem'], unique=False)
        batch_op.create_index('ix_manifests_scan_run_id', ['scan_run_id'], unique=False)

    op.create_table('provider_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'PARTIAL', 'RATE_LIMITED', 'UNAVAILABLE', 'NOT_REQUESTED', 'CACHED', 'UNKNOWN', name='provider_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('records_returned', sa.Integer(), nullable=False),
    sa.Column('cache_status', sa.String(length=32), nullable=True),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_provider_observations_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_observations'))
    )
    with op.batch_alter_table('provider_observations', schema=None) as batch_op:
        batch_op.create_index('ix_provider_observations_scan_run_id_provider', ['scan_run_id', 'provider'], unique=False)
        batch_op.create_index('ix_provider_observations_status', ['status'], unique=False)

    op.create_table('scan_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.Enum('REPOSITORY_INTAKE', 'ARCHIVE_VALIDATION', 'MANIFEST_DISCOVERY', 'DEPENDENCY_PARSING', 'DEPENDENCY_ENRICHMENT', 'VULNERABILITY_QUERY', 'WORKFLOW_ANALYSIS', 'REPOSITORY_POSTURE', 'FINDING_RECONCILIATION', 'EXPORT_GENERATION', name='stage_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'SKIPPED', name='stage_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_status', sa.String(length=32), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_summary', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_scan_stages_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_stages'))
    )
    with op.batch_alter_table('scan_stages', schema=None) as batch_op:
        batch_op.create_index('ix_scan_stages_scan_run_id', ['scan_run_id'], unique=False)
        batch_op.create_index('ix_scan_stages_status', ['status'], unique=False)

    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('manifest_id', sa.Integer(), nullable=False),
    sa.Column('ecosystem', sa.String(length=64), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('version_source', sa.Enum('MANIFEST', 'LOCKFILE', 'OVERRIDE', 'UNRESOLVED', 'UNKNOWN', name='component_version_source'), nullable=False),
    sa.Column('package_url', sa.String(length=512), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('relationship', sa.String(length=64), nullable=True),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('development', sa.Boolean(), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('integrity', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("package_name NOT LIKE '%..%'", name=op.f('ck_components_package_name_no_traversal')),
    sa.CheckConstraint('length(package_name) > 0', name=op.f('ck_components_package_name_not_empty')),
    sa.ForeignKeyConstraint(['manifest_id'], ['manifests.id'], name=op.f('fk_components_manifest_id_manifests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_components_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_components'))
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index('ix_components_ecosystem_package_name', ['ecosystem', 'package_name'], unique=False)
        batch_op.create_index('ix_components_manifest_id', ['manifest_id'], unique=False)
        batch_op.create_index('ix_components_scan_run_id_package_name', ['scan_run_id', 'package_name'], unique=False)

    op.create_table('component_advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('advisory_id', sa.Integer(), nullable=False),
    sa.Column('affected', sa.Integer(), nullable=False),
    sa.Column('fixed_versions_json', sa.String(length=2048), nullable=True),
    sa.Column('severity_source', sa.String(length=64), nullable=True),
    sa.Column('severity_label', sa.String(length=32), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(evidence_json) <= 65536', name=op.f('ck_component_advisories_evidence_bounded')),
    sa.CheckConstraint('severity_score IS NULL OR (severity_score >= 0 AND severity_score <= 10)', name=op.f('ck_component_advisories_severity_range')),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], name=op.f('fk_component_advisories_advisory_id_advisories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name=op.f('fk_component_advisories_component_id_components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_component_advisories_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_advisories')),
    sa.UniqueConstraint('scan_run_id', 'component_id', 'advisory_id', name='uq_component_advisories_scan_component_advisory')
    )
    with op.batch_alter_table('component_advisories', schema=None) as batch_op:
        batch_op.create_index('ix_component_advisories_advisory_id', ['advisory_id'], unique=False)
        batch_op.create_index('ix_component_advisories_component_id', ['component_id'], unique=False)
        batch_op.create_index('ix_component_advisories_scan_run_id', ['scan_run_id'], unique=False)

    op.create_table('dependency_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('parent_component_id', sa.Integer(), nullable=False),
    sa.Column('child_component_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('depth >= 0', name=op.f('ck_dependency_edges_depth_non_negative')),
    sa.CheckConstraint('parent_component_id <> child_component_id', name=op.f('ck_dependency_edges_no_self_reference')),
    sa.ForeignKeyConstraint(['child_component_id'], ['components.id'], name=op.f('fk_dependency_edges_child_component_id_components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_component_id'], ['components.id'], name=op.f('fk_dependency_edges_parent_component_id_components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_dependency_edges_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependency_edges')),
    sa.UniqueConstraint('scan_run_id', 'parent_component_id', 'child_component_id', name='uq_dependency_edges_parent_child')
    )
    with op.batch_alter_table('dependency_edges', schema=None) as batch_op:
        batch_op.create_index('ix_dependency_edges_child', ['child_component_id'], unique=False)
        batch_op.create_index('ix_dependency_edges_parent', ['parent_component_id'], unique=False)
        batch_op.create_index('ix_dependency_edges_scan_run_id', ['scan_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependency_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_dependency_edges_scan_run_id')
        batch_op.drop_index('ix_dependency_edges_parent')
        batch_op.drop_index('ix_dependency_edges_child')

    op.drop_table('dependency_edges')
    with op.batch_alter_table('component_advisories', schema=None) as batch_op:
        batch_op.drop_index('ix_component_advisories_scan_run_id')
        batch_op.drop_index('ix_component_advisories_component_id')
        batch_op.drop_index('ix_component_advisories_advisory_id')

    op.drop_table('component_advisories')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index('ix_components_scan_run_id_package_name')
        batch_op.drop_index('ix_components_manifest_id')
        batch_op.drop_index('ix_components_ecosystem_package_name')

    op.drop_table('components')
    with op.batch_alter_table('scan_stages', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_stages_status')
        batch_op.drop_index('ix_scan_stages_scan_run_id')

    op.drop_table('scan_stages')
    with op.batch_alter_table('provider_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_provider_observations_status')
        batch_op.drop_index('ix_provider_observations_scan_run_id_provider')

    op.drop_table('provider_observations')
    with op.batch_alter_table('manifests', schema=None) as batch_op:
        batch_op.drop_index('ix_manifests_scan_run_id')
        batch_op.drop_index('ix_manifests_ecosystem')

    op.drop_table('manifests')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_severity')
        batch_op.drop_index('ix_findings_scan_run_id')
        batch_op.drop_index('ix_findings_rule_id')
        batch_op.drop_index('ix_findings_repository_id')
        batch_op.drop_index('ix_findings_category')

    op.drop_table('findings')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_runs_status')
        batch_op.drop_index('ix_scan_runs_repository_id_created_at')
        batch_op.drop_index('ix_scan_runs_repository_id')

    op.drop_table('scan_runs')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index('ix_repositories_source_type')
        batch_op.drop_index('ix_repositories_provider_owner')

    op.drop_table('repositories')
    with op.batch_alter_table('advisories', schema=None) as batch_op:
        batch_op.drop_index('ix_advisories_published_at')
        batch_op.drop_index('ix_advisories_canonical_id')

    op.drop_table('advisories')
    # ### end Alembic commands ###
