import { Link } from "react-router";
import {
  AlertOctagon,
  BookOpen,
  EyeOff,
  FileSearch,
  PlayCircle,
  Sparkles,
  XCircle,
} from "lucide-react";

import { DataCompletenessNotice } from "@/components/DataCompletenessNotice";
import { PageHeader } from "@/components/PageHeader";

/**
 * In-app reviewer / demo home.
 *
 * The v1.4 page a reviewer lands on after starting the local
 * demo. It enumerates the demo dataset's nature, the main
 * reviewer flow (one link per documented surface), the
 * "what to look for" and "what not to claim" framings, and a
 * short command reminder. The page is intentionally simple,
 * read-only, and free of API calls; the live surfaces
 * downstream are the canonical evidence.
 */
export function DemoHomePage() {
  return (
    <>
      <PageHeader
        title="Local demo"
        description="A 60-second guided walkthrough of the Lockverity v2.1.0 demo. The five pages below cover every v0.5–v2.1.0 surface; the live demo is the canonical evidence."
        breadcrumbs={[{ label: "Demo" }]}
      />
      <div className="space-y-6">
        <section aria-labelledby="demo-dataset-status" className="card">
          <h2
            id="demo-dataset-status"
            className="flex items-center gap-2 text-base font-semibold text-ink-900"
          >
            <Sparkles aria-hidden="true" className="h-4 w-4 text-accent-700" />
            Demo dataset status
          </h2>
          <p className="mt-2 text-sm text-ink-700">
            The four scans in this demo are{" "}
            <strong>synthetic persisted evidence</strong> generated by{" "}
            <code>backend/scripts/load_demo.py</code>:
          </p>
          <ul className="mt-2 ml-5 list-disc space-y-1 text-sm text-ink-700">
            <li>The fixture repository is the canonical <code>example-org/lockverity-fixture</code>; the resolved commit SHA is the <code>deadbeef</code> repeated fill.</li>
            <li>Every package name is from the documented six-name set: <code>alpha</code>, <code>beta</code>, <code>gamma</code>, <code>left-pad</code>, <code>right-pad</code>, <code>stay</code>.</li>
            <li>The loader runs the same Alembic migrations the application uses; it never calls <code>Base.metadata.create_all</code> as the primary schema creator.</li>
            <li>
              <strong>No provider calls are made by the demo loader.</strong>{" "}
              The three provider observations on scan 1 (<code>osv</code>, <code>osv</code>, <code>deps_dev</code>) are explicit seeded rows, not live provider responses.
            </li>
            <li>
              <strong>No analyzed repository code is executed.</strong> The
              scanner never invokes <code>npm install</code>,{" "}
              <code>pip install</code>, <code>poetry install</code>,{" "}
              <code>yarn install</code>, <code>pnpm install</code>,{" "}
              <code>setup.py</code>, or any Makefile / shell script.
            </li>
          </ul>
        </section>

        <section aria-labelledby="demo-flow" className="card">
          <h2
            id="demo-flow"
            className="flex items-center gap-2 text-base font-semibold text-ink-900"
          >
            <PlayCircle aria-hidden="true" className="h-4 w-4 text-accent-700" />
            Reviewer flow
          </h2>
          <p className="mt-2 text-sm text-ink-700">
            Open the five pages below in order. Each page surfaces one
            v0.5–v1.4 surface; the live demo is the canonical evidence
            behind every claim.
          </p>
          <ol className="mt-3 ml-5 list-decimal space-y-2 text-sm text-ink-700">
            <li>
              <Link
                to="/"
                className="font-mono text-accent-700 hover:text-accent-800"
              >
                /
              </Link>{" "}
              — <strong>Scan list</strong>. Four scans with the v2.1.0 demo
              notice above them. Status badges: emerald (completed), amber
              (partial), rose (failed), ink-100 (cancelled).
            </li>
            <li>
              <Link
                to="/scans/1/dependencies"
                className="font-mono text-accent-700 hover:text-accent-800"
              >
                /scans/1/dependencies
              </Link>{" "}
              — <strong>Dependency Explorer</strong>. 6 components, 9
              filter fields, 13 facet counts. Type <code>left</code> in
              the search box to narrow the table to{" "}
              <code>left-pad</code>; click <em>View evidence</em> to open
              the v0.8 per-component drilldown.
            </li>
            <li>
              <Link
                to="/scans/1/exports"
                className="font-mono text-accent-700 hover:text-accent-800"
              >
                /scans/1/exports
              </Link>{" "}
              — <strong>Export Center</strong>. Click{" "}
              <em>Show CycloneDX 1.7 evidence preview</em> for the
              v0.7 eligibility verdict, then click{" "}
              <em>Show report summary</em> for the v1.0 evidence report
              preview. Both download flows are deterministic.
            </li>
            <li>
              <Link
                to="/scans/3/exports"
                className="font-mono text-accent-700 hover:text-accent-800"
              >
                /scans/3/exports
              </Link>{" "}
              — <strong>Failed scan bounded empty state</strong>. 0
              components, <code>not_applicable</code> coverage, the
              bounded &ldquo;no components recorded&rdquo; wording. The UI does{" "}
              <strong>not</strong> fabricate a clean verdict for a
              failed scan.
            </li>
            <li>
              <Link
                to="/scans/4/exports"
                className="font-mono text-accent-700 hover:text-accent-800"
              >
                /scans/4/exports
              </Link>{" "}
              — <strong>Cancelled scan bounded empty state</strong>. Same
              bounded <code>not_applicable</code> empty state.
            </li>
            <li>
              <Link
                to="/about"
                className="font-mono text-accent-700 hover:text-accent-800"
              >
                /about
              </Link>{" "}
              — <strong>About page + product boundaries</strong>. The
              current milestone, the v1.0 evidence report bullet, the
              bounded <em>What v2.1.0 does not include</em> section, the
              provider-honesty and non-execution guarantees.
            </li>
          </ol>
        </section>

        <section aria-labelledby="demo-look-for" className="card">
          <h2
            id="demo-look-for"
            className="flex items-center gap-2 text-base font-semibold text-ink-900"
          >
            <FileSearch aria-hidden="true" className="h-4 w-4 text-accent-700" />
            What to look for
          </h2>
          <ul className="mt-2 ml-5 list-disc space-y-1 text-sm text-ink-700">
            <li>
              The 9 evidence filter fields + 13 facet counts on the
              Dependency Explorer; the vocabulary itself is
              evidence-honest.
            </li>
            <li>
              The v0.8 component evidence drilldown with 6 sections +
              the evidence-honesty markers list at the bottom.
            </li>
            <li>
              The v0.7 CycloneDX 1.7 evidence preview surfaces the
              eligibility verdict <em>before</em> the SBOM is downloaded.
            </li>
            <li>
              The v1.0 Markdown evidence report with the bounded
              disclaimer:{" "}
              <em>
                &ldquo;This is an evidence report, not a security verdict, not
                a certification, and not a compliance pass-or-fail.&rdquo;
              </em>
            </li>
            <li>
              The bounded <code>not_applicable</code> empty state on
              scans 3 and 4; the UI does not fabricate a clean verdict
              for a failed or cancelled scan.
            </li>
            <li>
              The v2.1.0 demo-dataset notice above the scan list; the
              notice does not appear on real repositories.
            </li>
          </ul>
        </section>

        <section aria-labelledby="demo-not-claim" className="card">
          <h2
            id="demo-not-claim"
            className="flex items-center gap-2 text-base font-semibold text-ink-900"
          >
            <AlertOctagon aria-hidden="true" className="h-4 w-4 text-rose-700" />
            What not to claim
          </h2>
          <ul className="mt-2 ml-5 list-disc space-y-2 text-sm text-ink-700">
            <li>
              <EyeOff aria-hidden="true" className="-mt-1 mr-1 inline h-4 w-4 text-ink-500" />
              Do <strong>not</strong> call the report{" "}
              <em>&ldquo;a security scan result&rdquo;</em>. It is an evidence report.
            </li>
            <li>
              <XCircle aria-hidden="true" className="-mt-1 mr-1 inline h-4 w-4 text-ink-500" />
              Do <strong>not</strong> call the SBOM{" "}
              <em>&ldquo;a certified bill of materials&rdquo;</em>. It is evidence;
              the schema validates, but the export is not signed and
              does not carry a trust assertion.
            </li>
            <li>
              <XCircle aria-hidden="true" className="-mt-1 mr-1 inline h-4 w-4 text-ink-500" />
              Do <strong>not</strong> say{" "}
              <em>&ldquo;the dependency graph is complete&rdquo;</em> unless a
              positive persisted signal exists. The v0.6 helper returns{" "}
              <code>partial</code> for the demo dataset.
            </li>
            <li>
              <XCircle aria-hidden="true" className="-mt-1 mr-1 inline h-4 w-4 text-ink-500" />
              Do <strong>not</strong> say{" "}
              <em>&ldquo;no findings&rdquo;</em> because a provider was unavailable,
              rate-limited, or skipped. The demo&rsquo;s three provider
              observations are explicit <code>AVAILABLE</code> or{" "}
              <code>RATE_LIMITED</code> rows, never silent omissions.
            </li>
            <li>
              <XCircle aria-hidden="true" className="-mt-1 mr-1 inline h-4 w-4 text-ink-500" />
              Do <strong>not</strong> call the demo dataset a real
              provider scan result. The fixture repository is
              <code>example-org/lockverity-fixture</code> and the
              resolved commit SHA is the <code>deadbeef</code> fill.
            </li>
          </ul>
        </section>

        <section aria-labelledby="demo-commands" className="card">
          <h2
            id="demo-commands"
            className="flex items-center gap-2 text-base font-semibold text-ink-900"
          >
            <BookOpen aria-hidden="true" className="h-4 w-4 text-accent-700" />
            Quick command reminder
          </h2>
          <p className="mt-2 text-sm text-ink-700">
            The demo runs the backend on <code>127.0.0.1:8765</code> and
            the Vite dev server on <code>127.0.0.1:5173</code>. PowerShell
            one-liners:
          </p>
          <pre className="mt-3 overflow-x-auto rounded-md border border-ink-200 bg-ink-50 p-3 text-xs text-ink-800"><code>{`cd backend
.\\.venv\\Scripts\\python.exe scripts\\load_demo.py --reset-demo-db
$env:LOCKVERITY_DATABASE_URL = "sqlite:///var/demo/lockverity-demo.sqlite"
.\\.venv\\Scripts\\python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8765

cd frontend
$env:VITE_API_PROXY_TARGET = "http://127.0.0.1:8765"
npm install
npm run dev`}</code></pre>
        </section>

        <section aria-labelledby="demo-beyond" className="card">
          <h2
            id="demo-beyond"
            className="flex items-center gap-2 text-base font-semibold text-ink-900"
          >
            <Sparkles aria-hidden="true" className="h-4 w-4 text-accent-700" />
            Beyond the demo
          </h2>
          <p className="mt-2 text-sm text-ink-700">
            The v1.5 guided intake page lets you analyze a public
            GitHub repository or upload a <code>.zip</code> source
            archive on top of the seeded demo. The page reuses the
            same intake endpoints the rest of the application uses;
            it does not duplicate business logic in the frontend.
          </p>
          <ul className="mt-2 ml-5 list-disc space-y-1 text-sm text-ink-700">
            <li>
              <Link
                to="/analyze"
                className="font-mono text-accent-700 hover:text-accent-800"
              >
                /analyze
              </Link>{" "}
              &mdash; Public GitHub URL or ZIP upload, navigate to the new scan.
            </li>
            <li>
              Public repositories only. Lockverity never asks for,
              stores, or sends a personal access token from the
              browser.
            </li>
            <li>
              Archives are treated as hostile input. Entries are
              validated before extraction; uploaded code is never
              executed.
            </li>
          </ul>
        </section>

        <DataCompletenessNotice
          title="This is a demo, not a hosted service"
          description="The application has no authentication, no multi-tenancy, and no hosted control plane. The reviewer runs the demo on their own laptop; Lockverity makes no provider calls during the demo. The current status is a local-first, portfolio-ready release candidate; the public/private recommendation is in docs/demo-pack.md."
          tone="muted"
        />
      </div>
    </>
  );
}
