import { useEffect, useState } from "react";
import { Link, useParams } from "react-router";

import { api } from "@/api/api";
import type { Scan } from "@/api/types";
import { DataCompletenessNotice } from "@/components/DataCompletenessNotice";
import { EmptyState } from "@/components/EmptyState";
import { ErrorState } from "@/components/ErrorState";
import { LoadingState } from "@/components/LoadingState";
import { PageHeader } from "@/components/PageHeader";
import { ResponsiveTable } from "@/components/ResponsiveTable";
import { StatusBadge } from "@/components/StatusBadge";
import { formatRelative } from "@/utils/time";

const DEMO_FIXTURE_CANONICAL_URL =
  "https://github.com/example-org/lockverity-fixture";

/**
 * Index of all known scans, paginated across repositories.
 * Used when a user lands on /scans without a specific id.
 */
export function ScansIndexPage() {
  const [items, setItems] = useState<Scan[] | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [isDemoFixture, setIsDemoFixture] = useState<boolean>(false);
  const params = useParams();

  useEffect(() => {
    if (params.scanId) return; // not our route
    const controller = new AbortController();
    (async () => {
      try {
        const repos = await api.listRepositories({ page: 1, page_size: 50 });
        const results = await Promise.all(
          repos.items.map((repo) =>
            api.listScansForRepository(repo.id, { page: 1, page_size: 5 }).catch(() => null)
          )
        );
        const flat: Scan[] = [];
        for (const r of results) {
          if (r) flat.push(...r.items);
        }
        flat.sort((a, b) => (a.created_at < b.created_at ? 1 : -1));
        if (controller.signal.aborted) return;
        setItems(flat);
        // Render the demo-dataset notice only when every
        // listed scan belongs to the synthetic demo
        // fixture repository. The detection is robust
        // against arbitrary repository ids because it
        // checks the actual canonical URL.
        const demoRepoIds = new Set(
          repos.items
            .filter((repo) => repo.canonical_url === DEMO_FIXTURE_CANONICAL_URL)
            .map((repo) => repo.id)
        );
        setIsDemoFixture(
          flat.length > 0 &&
            flat.every((scan) => demoRepoIds.has(scan.repository_id))
        );
      } catch (err) {
        if (!controller.signal.aborted) setError(err);
      }
    })();
    return () => controller.abort();
  }, [params.scanId]);

  if (error) {
    return (
      <>
        <PageHeader title="Scans" />
        <ErrorState error={error} />
      </>
    );
  }
  if (items === null) {
    return (
      <>
        <PageHeader title="Scans" />
        <LoadingState label="Loading scans" />
      </>
    );
  }

  return (
    <>
      <PageHeader
        title="Scans"
        description="Recent scans across all repositories."
      />
      {isDemoFixture ? (
        <div className="mb-4">
          <DataCompletenessNotice
            title="Demo evidence: synthetic persisted dataset"
            description="Generated by Lockverity's demo loader (backend/scripts/load_demo.py). No provider calls were made; package names, versions, and the resolved commit SHA are obviously synthetic. The report and the SBOM are evidence exports, not a security verdict, certification, or compliance pass-or-fail."
            tone="muted"
          />
        </div>
      ) : null}
      {items.length === 0 ? (
        <EmptyState
          title="No scans yet"
          description="Analyze a public GitHub repository or upload a source archive to start your first scan. You can also open the demo guide to walk through a seeded synthetic dataset."
          action={
            <div className="flex flex-wrap items-center justify-center gap-2">
              <Link to="/analyze" className="btn-primary">
                Analyze repository
              </Link>
              <Link to="/demo" className="btn-secondary">
                Open demo guide
              </Link>
            </div>
          }
        />
      ) : (
        <ResponsiveTable headers={["Scan", "Status", "Repository", "Created"]}>
          {items.map((scan) => (
            <tr key={scan.id} className="table-row">
              <td className="table-cell">
                <Link
                  to={`/scans/${scan.id}`}
                  className="text-ink-900 hover:text-accent-700"
                >
                  #{scan.id}
                </Link>
              </td>
              <td className="table-cell">
                <StatusBadge status={scan.status} />
              </td>
              <td className="table-cell text-ink-500">
                <Link
                  to={`/repositories/${scan.repository_id}`}
                  className="hover:text-accent-700"
                >
                  repo #{scan.repository_id}
                </Link>
              </td>
              <td className="table-cell text-ink-500">
                {formatRelative(scan.created_at)}
              </td>
            </tr>
          ))}
        </ResponsiveTable>
      )}
    </>
  );
}
